#!/usr/bin/env bash

# get the dir of the current script
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) && cd "$SCRIPT_DIR" || exit 1

# show usage and quit
usage() {
    echo "Usage: $0 <module> [module]..." >&2
    exit 1
}

[[ "$#" -lt 1 ]] && usage

info()  { printf "%b[info]%b  %s\n" '\e[0;32m' '\e[0m' "$@" >&2; }
error() { printf "%b[error]%b %s\n" '\e[0;31m' '\e[0m' "$@" >&2; }

install_module() {
    local module="$1"
    info "install $module config ..."
    [[ ! -f "$module/setup.sh" ]] && error "$module config not found!" && return
    "$module/setup.sh"            && info  "$module config installed successfully!"
}

for module in "$@"; do
    install_module "${module%/}"
done
