#!/usr/bin/env bash

# get the dir of the current script
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) && cd "$SCRIPT_DIR" || exit 1

# show usage and quit
usage() {
    echo "Usage: $0 <module> [module]..." >&2
    exit 1
}

[[ "$#" -lt 1 ]] && usage

# source color code
source scripts/color.sh

info() { printf "%b[Info]%b %s\n" "$GRN" "$RST" "$@" >&2; }

install_module() {
    local module="$1"
    printf "${BLU}install $module config ...${RST}\n"
    [[ ! -f "$module/setup.sh" ]] && printf "${RED}$module config not found!${RST}\n" && return
    # "$module/setup.sh"            && printf "${GRN}$module config installed successfully!${RST}\n"
    printf "${GRN}$module config installed successfully!${RST}\n"
}

for module in "$@"; do
    install_module "${module%/}"
done
