#!/usr/bin/env bash

# get the dir of the current script
SDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) && cd "$SDIR" || exit 1

# show usage and quit
usage() { echo "Usage: $(basename "$0") <module> [module]..." >&2; }

[[ "$#" -lt 1 ]] && usage && exit 1

loginfo()  { printf "%b[info]%b %s\n"  '\e[0;32m\033[1m' '\e[0m' "$@" >&2; }
logwarn()  { printf "%b[warn]%b %s\n"  '\e[0;33m\033[1m' '\e[0m' "$@" >&2; }
logerror() { printf "%b[error]%b %s\n" '\e[0;31m\033[1m' '\e[0m' "$@" >&2; }

install_module() {
    local module="$1"
    loginfo "install $module config ..."
    [[ ! -f "$module/setup.sh" ]] && logerror "$module config not found!" && return 2
    "$module/setup.sh"            && loginfo  "$module config installed successfully!"
}

for module in "$@"; do
    install_module "${module%/}"
done
