"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
append_keymap = [
    { on = "<C-p>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<C-n>", run = "arrow 1",  desc = "Move cursor down" },
]

[input]
prepend_keymap = [
    { on = "<Esc>", run = "close", desc = "Cancel input" },
]

# Plugin keymap
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
