scriptencoding utf-8
set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L
set guitablabel=%M\ %t

if has('win32') || has('win64')
    let g:is_win = 1
else
    let g:is_win = 0
endif

if g:is_win
    " set guifont=JetBrains\ Mono:h12:cANSI
    " Request after changing the version of language
    source $VIMRUNTIME/delmenu.vim
    source $VIMRUNTIME/menu.vim
    " Avoid messy code under console
    language messages en_US
endif

set guifont=JetBrains\ Mono\ 12
