"=============================================================================
"       Author: Wenxuan Zhang
"        Email: wenxuangm@gmail.com
"     HomePage: wenxuan.info
"=============================================================================

if has("win32") || has("win64")
    let g:isWIN = 1
else
    let g:isWIN = 0
endif

" Cancel compatible to avoid some bugs and limitations.
set nocompatible

source ~/.vim_base
source ~/.vim_plug
source ~/.vim_map

"if has("termguicolors") && has("nvim")
    "set termguicolors
"endif
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Change to English version. (Replaced 'en_US' by 'zh_CN' for Chinese)
let $LANG = 'en_US'
set langmenu=en_US

" Add 'cjk' to spelllang to avoid checking Chinese
set spelllang+=cjk

" Use spell check
"setlocal spell

" Enable mouse
set mouse=a

" Linebrake on 90 characters
set linebreak
"set textwidth=100
set wrap

" Hilight current line
"set cursorline

" Make '<', '>', 'h', 'l' work properly.
set whichwrap+=<,>,h,l

" Set how many lines of history Vim will remember
set history=1000

" Don't redraw while executing macros (good performance config)
set lazyredraw

" Show row number
set number
" Show relative number
"set relativenumber

" Set height of cmd line to 2
set cmdheight=1

" Highlight search matches
set hlsearch

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second (i.e. x/10 s) to blink when matching brackets
set matchtime=2

" Ignore compiled files
set wildignore=*.o,*~,*.pyc
set wildmode=full

" Set auto indent and C/C++ indent
set smartindent
set cindent

" Use Unix as the standard file type
set fileformat=unix
set fileformats=unix,dos,mac

" Set the sequence of auto encoding
set fileencodings=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936,big5
set encoding=utf-8

" No swap files, use version control instead
set noswapfile

set diffopt=vertical

" Mark conceal level
set conceallevel=2

"¦ ┆ │ ⎸ ▏
set fillchars+=vert:¦

" Default 800ms is too slow
set updatetime=500

" Default 1000ms is too long
set timeoutlen=400

" Set spell in certain cases
autocmd FileType text,markdown,gitcommit setlocal spell

" Have Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

"function s:update_header()
    "let time = substitute(system("date +'%F %H:%M'"), '\n$', '', '')
    "execute 's/\( Modified: \).\{10\} .\{5}$/\1' . time . '/'
"endfunction
"command! UpdateHeader call s:update_header()
"autocmd BufWritePre * silent! :UpdateHeader " Update header when saving buffer

" disable Background Color Erase (BCE) so that color schemes
" render properly when inside 256-color tmux and GNU screen.
" see also http://snk.tuxfamily.org/log/vim-256color-bce.html
if !has("nvim") && &term =~ '256color'
  set t_ut=
endif

colorscheme gruvbox
set background=dark
" Transparent setting
hi VertSplit ctermbg=NONE guibg=NONE
hi Normal ctermbg=none guibg=NONE

" Show changes since last save
function! s:DiffSaved()
  let filetype=&ft
  diffthis
  vnew | r # | normal! 1Gdd
  diffthis
  exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
command! DS call s:DiffSaved()

" Split and open terminal
command! -nargs=* T split | terminal <args>
command! -nargs=* VT vsplit | terminal <args>

" Add custom filetypes detection for ultisnips
au BufRead,BufNewFile pom.xml set filetype=maven.xml
au BufRead,BufNewFile build.gradle set filetype=gradle.groovy
