# RPK Config File
#
# See the documentation for more https://github.com/wfxr/rpk#readme

[pkgs.rpk]
repo = "wfxr/rpk"
desc = "A lightweight, cross-platform cli package manager."

[pkgs.fd]
repo = "sharkdp/fd"
desc = "A simple, fast and user-friendly alternative to 'find'"

[pkgs.rg]
repo = "BurntSushi/ripgrep"
desc = "ripgrep recursively searches directories for a regex pattern while respecting your gitignore"

[pkgs.delta]
repo = "dandavison/delta"
desc = "A syntax-highlighting pager for git, diff, grep, and blame output"

[pkgs.eza]
repo = "eza-community/eza"
desc = "A modern alternative to ls"

[pkgs.dua]
repo = "Byron/dua-cli"
desc = "View disk space usage and delete unwanted data, fast."

[pkgs.mmv]
repo = "itchyny/mmv"
desc = "rename multiple files with editor"

[pkgs.gh]
repo = "cli/cli"
desc = "GitHub’s official command line tool"

[pkgs.bat]
repo = "sharkdp/bat"
desc = "A cat(1) clone with wings."

[pkgs.jq]
repo = "jqlang/jq"
desc = "Command-line JSON processor"

[pkgs.sheldon]
repo = "rossmacarthur/sheldon"
desc = ":bowtie: Fast, configurable, shell plugin manager"

[pkgs.zoxide]
repo = "ajeetdsouza/zoxide"
desc = "A smarter cd command. Supports all major shells."

[pkgs.duf]
repo = "muesli/duf"
desc = "Disk Usage/Free Utility - a better 'df' alternative"

[pkgs.btm]
repo = "ClementTsang/bottom"
desc = "Yet another cross-platform graphical process/system monitor."

[pkgs.sd]
repo = "chmln/sd"
desc = "Intuitive find & replace CLI (sed alternative)"

[pkgs.fzf]
repo = "junegunn/fzf"
desc = ":cherry_blossom: A command-line fuzzy finder"

[pkgs.hexyl]
bins = ["hexyl"]
repo = "sharkdp/hexyl"
desc = "A command-line hex viewer"

[pkgs.fastfetch]
bins = ["fastfetch"]
repo = "fastfetch-cli/fastfetch"
desc = "A maintained, feature-rich and performance oriented, neofetch like system information tool."

[pkgs.yazi]
bins = [
    "yazi",
    "ya",
]
repo = "sxyazi/yazi"
desc = "💥 Blazing fast terminal file manager written in Rust, based on async I/O."

[pkgs.procs]
bins = ["procs"]
repo = "dalance/procs"
desc = "A modern replacement for ps written in Rust"

[pkgs.lazydocker]
bins = ["lazydocker"]
repo = "jesseduffield/lazydocker"
desc = "The lazier way to manage everything docker"
