#!/usr/bin/env bash
################################################################################
#    Author: Wenxuan Zhang                                                     #
#     Email: wenxuangm@gmail.com                                               #
#   Created: 2019-11-30 17:16                                                  #
################################################################################

main() {
    variety &>/tmp/variety.log &
    return 0
}

main
