#!/usr/bin/env bash
################################################################################
#    Author: Wenxuan Zhang                                                     #
#     Email: wenxuangm@gmail.com                                               #
#   Created: 2019-11-30 17:16                                                  #
################################################################################

start_polybar() {
    # Terminate already running bar instances
    killall -q polybar

    # Wait until the processes have been shut down
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

    # Launch bar
    polybar top &>/tmp/polybar-top.log &
}

start_tmux() {
    # we cant not keep a tmux server without any session by using `tmux start-server`
    # https://github.com/tmux/tmux/issues/182
    # tmux start-server &
    if ! tmux has-session -t 'default'; then
        tmux new-session -d -s 'defalut' &
    fi
}


main() {
    start_polybar
    start_tmux
}

main
