#!/usr/bin/env zsh
#===============================================================================
#   Author: Wenxuan
#    Email: wenxuangm@gmail.com
#  Created: 2017-12-23 15:02
#===============================================================================

#######################################################################
#                               Common                                #
#######################################################################

[[ -n ${SSH_CLIENT} ]] && PROMPT_SYMBOL=' ' || PROMPT_SYMBOL=''
TIME_FORMAT="%D{%H:%M}"
GITHUB_ICON=''
EXECUTION_TIME_ICON='' #   
EXECUTION_TIME_THRESHOLD=0.1

#######################################################################
#                              SPACESHIP                              #
#######################################################################
SPACESHIP_PROMPT_SYMBOL=" ${PROMPT_SYMBOL}"
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT="$TIME_FORMAT"
SPACESHIP_USER_PREFIX=""


# EXECUTION TIME
#SPACESHIP_EXEC_TIME_SHOW=true
#SPACESHIP_EXEC_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_EXEC_TIME_PREFIX="took "
#SPACESHIP_EXEC_TIME_COLOR="yellow"
#SPACESHIP_EXEC_TIME_THRESHOLD=2000

# DIR
#SPACESHIP_DIR_SHOW=true
#SPACESHIP_DIR_PREFIX="in "
#SPACESHIP_DIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DIR_TRUNC=5
#SPACESHIP_DIR_COLOR="cyan"

SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_RUBY_SHOW=false
SPACESHIP_ELIXIR_SHOW=false
SPACESHIP_XCODE_SHOW_LOCAL=false
SPACESHIP_SWIFT_SHOW_LOCAL=false
SPACESHIP_GOLANG_SHOW=false
SPACESHIP_PHP_SHOW=false
SPACESHIP_RUST_SHOW=false
SPACESHIP_JULIA_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_AWS_SHOW=false
SPACESHIP_VENV_SHOW=false
SPACESHIP_CONDA_SHOW=false
SPACESHIP_PYENV_SHOW=false
SPACESHIP_DOTNET_SHOW=false
SPACESHIP_EMBER_SHOW=false
SPACESHIP_KUBECONTEXT_SHOW=false

# JOBS
#SPACESHIP_JOBS_SHOW=true
#SPACESHIP_JOBS_PREFIX=""
#SPACESHIP_JOBS_SUFFIX=" "
#SPACESHIP_JOBS_SYMBOL="✦"
#SPACESHIP_JOBS_COLOR="blue"

# EXIT CODE
#SPACESHIP_EXIT_CODE_SHOW=false
#SPACESHIP_EXIT_CODE_PREFIX="("
#SPACESHIP_EXIT_CODE_SUFFIX=") "
#SPACESHIP_EXIT_CODE_SYMBOL="✘ "
#SPACESHIP_EXIT_CODE_COLOR="red"
