#!/usr/bin/env zsh
################################################################################
#       Author: Wenxuan Zhang                                                  #
#        Email: wenxuangm@gmail.com                                            #
#     HomePage: https://github.com/wfxr                                        #
################################################################################

# Plugin manager
[ -d ~/.zplugin/bin ] || {
    mkdir -p ~/.zplugin
    git clone --depth=1 https://github.com/zdharma/zplugin.git ~/.zplugin/bin
}
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

#######################################################################
# snippet plugins                                                     #
#######################################################################
zplugin light-mode as='null' cloneonly depth='1' nocompile for \
    'ohmyzsh/ohmyzsh'

OMZ="${ZPLGM[PLUGINS_DIR]}/ohmyzsh---ohmyzsh/plugins"

zplugin snippet "$OMZ/git/git.plugin.zsh"
zplugin snippet "$OMZ/git-extras/git-extras.plugin.zsh"
zplugin snippet "$OMZ/git-flow-avh/git-flow-avh.plugin.zsh"
zplugin snippet "$OMZ/mvn/mvn.plugin.zsh"
zplugin snippet "$OMZ/colored-man-pages/colored-man-pages.plugin.zsh"

zplugin ice as='completion'; zplugin snippet "$OMZ/docker/_docker"
zplugin ice as='completion'; zplugin snippet "$OMZ/gem/_gem"
zplugin ice as='completion'; zplugin snippet "$OMZ/lein/_lein"

#######################################################################
# normal plugins                                                      #
#######################################################################
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(forward-word forward-char)
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(end-of-line)
zplugin light-mode lucid wait depth='1' for \
    atload='_zsh_autosuggest_start' \
        'zsh-users/zsh-autosuggestions' \
    blockf \
        'zsh-users/zsh-completions' \
        'hlissner/zsh-autopair' \
        'zdharma/fast-syntax-highlighting' \
        'soimort/translate-shell'

FORGIT_FZF_DEFAULT_OPTS="--height '80%'"
zplugin light-mode lucid depth='1' for \
    'wfxr/forepos' \
    'wfxr/epoch-cli' \
    'wfxr/formarks' \
    'wfxr/forgit' \
    'rupa/z'
# 'skywind3000/z.lua' # better than rupa/z ?

#######################################################################
# programs                                                            #
#######################################################################
zlk() {
    if [ $# -eq 0 ] || [ $# -gt 3 ]; then
        errorlog "usage: zlk <from> [->] [dest]" && return 1
    fi
    local src="$1"
    local dest="$src"
    [ $# -eq 2 ] && dest="$2"
    [ $# -eq 3 ] && dest="$3"
    eval 'ln -sf $PWD/'"$src ~/bin/$dest"
}

zplugin light-mode as='null' cloneonly depth='1' nocompile for \
    atclone='zlk src/ydcv.py -> ydcv' \
        'felixonmars/ydcv' \
    atclone='zlk iconful.sh -> iconful' \
        'wfxr/iconful' \
    atclone='zlk b' \
        'wfxr/fzf-chrome-marks' \
    atclone='zlk diff-so-fancy && git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"' \
        'so-fancy/diff-so-fancy' \
    atclone="zlk httpstat.py -> httpstat" \
        'reorx/httpstat'

EMOJI_CLI_KEYBIND='^[m'
zplugin light-mode as='null' cloneonly depth='1' for \
    atclone='zlk emojify; zlk fuzzy-eomji' multisrc='*.zsh' \
        'wfxr/emoji-cli' \

zplugin light-mode as='program' from='gh-r' nocompile for \
    if='[[ -z $+commands[jq] ]]' mv="jq* -> jq" \
        'stedolan/jq'

#######################################################################
# theme plugins                                                       #
#######################################################################
(( $+commands[starship] )) && source <(starship init zsh)
[[ -f ~/.zsh_theme ]]      && source ~/.zsh_theme
# 'denysdovhan/spaceship-prompt'
# 'bhilburn/powerlevel9k'
# 'subnixr/minimal'
# 'mafredri/zsh-async'
# 'sindresorhus/pure'

#######################################################################
# local plugins                                                       #
#######################################################################
# https://gist.github.com/ctechols/ca1035271ad134841284
custom_compinit() {
    autoload -Uz compinit
    # once a day
    for dump in ~/.zcompdump(N.mh+24); do
        compinit
    done
    compinit -C
    zpcdreplay
}

zplg_async() {
    local name=$1; local cmd=$2; local delay=${3:-0}
    mkdir -p "${ZPLGM[PLUGINS_DIR]}/_local---$name"
    zplugin ice lucid wait="$delay" atload="$cmd"
    zplugin light "_local/$name"
}

zplg_async 'kubectl' '(( $+commands[kubectl] )) && source <(kubectl completion zsh)'

zplg_async 'python' '
(( $+commands[pyenv] )) && source <(pyenv init - zsh)
(( $+commands[pip]   )) && source <(pip completion --zsh)
'

# delay 1s to run compinit
zplg_async 'compinit' 'custom_compinit' 1
