#!/usr/bin/env zsh
#=============================================================================
#       Author: Wenxuan Zhang
#        Email: wenxuangm@gmail.com
#     HomePage: wenxuan.info
#=============================================================================

# Plugin manager
export ZPLUG_BIN=~/bin
export ZPLUG_THREADS=32
# If zplug doesn't exist, install it
ZPLUG_INIT=~/.zplug/init.zsh
[[ -f "$ZPLUG_INIT" ]] || curl -sL https://raw.githubusercontent.com/zplug/installer/master/installer.zsh |zsh
source "$ZPLUG_INIT"

zplug 'zplug/zplug', hook-build:'zplug --self-manage'
# No need to load it when in ssh session
[ "$SSH_CLIENT" ] || zplug "plugins/web-search",    from:oh-my-zsh, hook-load:"unalias map &>/dev/null"
[ "$SSH_CLIENT" ] || zplug 'wfxr/fzf-chrome-marks', as:command,     use:'b'

# Git alias. See: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git
zplug "plugins/git", from:oh-my-zsh
# Git completions. On OS X with Homebrew, you need to install git with brew install git --without-completions. Otherwise, git's _git will take precedence, and you won't see the completions for git-extras commands.
zplug "plugins/git-extras", from:oh-my-zsh
#zplug "plugins/cp", from:oh-my-zsh
(( $+commands[mvn]        )) && zplug "plugins/mvn",        from:oh-my-zsh, lazy:yes
(( $+commands[cargo]      )) && zplug "plugins/cargo",      from:oh-my-zsh, lazy:yes
(( $+commands[docker]     )) && zplug "plugins/docker",     from:oh-my-zsh, lazy:yes
(( $+commands[tmuxinator] )) && zplug "plugins/tmuxinator", from:oh-my-zsh, lazy:yes
(( $+commands[gem]        )) && zplug "plugins/gem",        from:oh-my-zsh, lazy:yes
(( $+commands[lein]       )) && zplug 'plugins/lein',       from:oh-my-zsh, lazy:yes
(( $+commands[odpscmd]    )) && zplug 'wfxr/odps-fzf'
zplug "plugins/colored-man-pages", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(forward-word forward-char)
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(end-of-line)

zplug "morhetz/gruvbox", use:"gruvbox_256palette.sh"
zplug "felixonmars/ydcv", as:command, use:"src/ydcv.py", rename-to:"ydcv"
#zplug 'ytet5uy4/fzf-widgets'
#bindkey '^@'  fzf-select-widget
#bindkey '^@ga' fzf-git-add-files

################################################################################
# Themes
################################################################################
zplug "wfxr/spaceship-zsh-theme", use:spaceship.zsh, as:theme
#zplug "denysdovhan/spaceship-zsh-theme", use:spaceship.zsh, as:theme
#zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme, as:theme
#zplug "b4b4r07/zsh-vimode-visual", use:"*.zsh", defer:3
#zplug "b4b4r07/ultimate", as:theme
#zplug "subnixr/minimal", as:theme, use:"minimal.zsh"
#zplug "mafredri/zsh-async", from:github
#zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
#if zplug check "b4b4r07/ultimate"; then
    #zstyle ':ultimate:prompt:path' mode 'shortpath'
#fi

zplug 'so-fancy/diff-so-fancy', \
    as:command, use:diff-so-fancy, \
    hook-build:'git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"'

zplug 'b4b4r07/zplug-doctor', lazy:yes

zplug 'wfxr/zplug-rm', lazy:yes
zplug 'wfxr/zplug-cd', lazy:yes
zplug 'wfxr/iconful', as:command, use:'(iconful).sh', rename-to:'$1'
zplug "wfxr/formarks"
zplug 'wfxr/forgit', defer:1
FORGIT_FZF_DEFAULT_OPTS="
--height '80%'
"
zplug "wfxr/emoji-cli", as:plugin
zplug "wfxr/emoji-cli", as:command, use:'emojify|fuzzy-emoji'
EMOJI_CLI_KEYBIND='^[m'
zplug 'wfxr/pbcopy', as:command, use:'(*).sh', rename-to:'$1'
zplug 'wfxr/epoch-cli', as:plugin

# A simple gist editor for CLI
#zplug "b4b4r07/gist", \
    #as:command, \
    #from:gh-r

# jq is a lightweight and flexible command-line JSON processor.
(( $+commands[jq] )) || zplug "stedolan/jq", as:command, from:gh-r, rename-to:jq

# Short, simple, direct scripts for creating ASCII graphical histograms in the terminal.
#zplug "philovivero/distribution", \
    #as:command, \
    #use:distribution

#zplug "holman/spark", \
    #as:command, \
    #use:spark

# httpstat visualizes curl(1) statistics in a way of beauty and clarity.
zplug "reorx/httpstat", \
    as:command, \
    use:'(httpstat).py', \
    rename-to:'$1'

# wrk - a HTTP benchmarking tool
# eg: wrk -t12 -c400 -d30s http://127.0.0.1:8080/index.html
#zplug "wg/wrk", \
    #as:command, \
    #hook-build:"make -j8"

# An interactive way to peruse your git history from the terminal
#zplug 'Fakerr/git-recall', \
    #as:command, \
    #use:'git-recall'

# Remote repository management made easy
zplug "motemen/ghq", \
    as:command, \
    from:gh-r, \
    rename-to:ghq

# sparklines
# usage: sparklines -n 3 null 3 7 4 2 5 6 | lolcat
#zplug "deeplook/sparklines", hook-build:"sudo pip install -e ."

#[[ ${(L)OSNAME} =~ darwin ]] && zplug "plugins/osx",       from:oh-my-zsh
#[[ ${(L)OSNAME} =~ ubuntu ]] && zplug "plugins/ubuntu",    from:oh-my-zsh
#[[ ${(L)OSNAME} =~ arch   ]] && zplug "plugins/archlinux", from:oh-my-zsh
#case ${(L)OSNAME} in
    #*arch* )
        #zplug "plugins/archlinux", from:oh-my-zsh ;;
    #*ubuntu* )
        #zplug "plugins/ubuntu", from:oh-my-zsh ;;
    #*darwin* )
        #zplug "plugins/darwin", from:oh-my-zsh ;;
#esac

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    read -q && echo && zplug install
fi

zplug load
