#!/usr/bin/env zsh
# vim: foldmethod=marker foldenable:

# xdg directories
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_VIDEOS_DIR="$HOME/Videos"
export XDG_SCREENSHOTS_DIR="$HOME/Screenshots"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

export GPG_TTY="$(tty)"

export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/usr/games:/usr/local/games:/bin:/sbin"

[[ $OSTYPE =~ darwin ]] && export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
[[ -x /home/linuxbrew/.linuxbrew/bin/brew ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# True color
export COLORTERM=truecolor

# Ruby
PATH="$HOME/.gem/bin:$HOME/.rbenv/bin:$PATH"

# C++
export CC="${commands[gcc]:-$CC}"
export CC="${commands[clang]:-$CC}"
export CXX="${commands[g++]:-$CXX}"
export CXX="${commands[clang++]:-$CXX}"

# Rust
PATH="$HOME/.cargo/bin:$PATH"
export CARGO_HOME="$HOME/.cargo"
export CARGO_TARGET_DIR="$HOME/.cache/cargo/target"

export TERM="xterm-256color"

# LANGUAGE must be set by en_US
export LANGUAGE="en_US.UTF-8"
export LANG="${LANGUAGE}"
export LC_ALL="${LANGUAGE}"
export LC_CTYPE="${LANGUAGE}"

# Editor
export EDITOR="${commands[vim]:-$EDITOR}"
export EDITOR="${commands[nvim]:-$EDITOR}"
export CVSEDITOR="${EDITOR}"
export GIT_EDITOR="${EDITOR}"
export VISUAL="${EDITOR}"

# Homebrew Bottles 中科大源
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"

# Golang
export GOPATH="$HOME/.go"
PATH="$GOPATH/bin:$PATH"

# Less
export LESS="-r -f -F -X -i -P ?f%f:(stdin). ?lb%lb?L/%L.. [?eEOF:?pb%pb\%..]"
export LESSCHARSET="utf-8"
# Pager
export PAGER="${commands[less]:-$PAGER}"

# Word split
export WORDCHARS=''

# Custom zsh completions path
export CUSTOM_FPATH="$XDG_CONFIG_HOME/zsh/completions"
export fpath=($fpath "$CUSTOM_FPATH")

# LS COLORS
# https://github.com/ogham/exa/blob/adfee28fb9bb6f491c822ba4506fafef03909945/Vagrantfile#L163
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
# https://github.com/sharkdp/vivid
# if (( $+commands[vivid] )); then
    # export LS_COLORS="$(vivid generate molokai)"
    # https://the.exa.website/docs/colour-themes#colour-codes
    # (( $+commands[exa] )) && export EXA_COLORS="$(vivid --color-mode 8-bit generate molokai)"
# fi

# For emacsclient
export ALTERNATE_EDITOR=""

# For lein
(( $+commands[drip] )) && export LEIN_JAVA_CMD='drip'

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PYTHON_CONFIGURE_OPTS="--enable-shared"
PATH="$HOME/.pyenv/shims:$PYENV_ROOT/bin:$PATH"

# bat
export BAT_CONFIGPATH="$HOME/.config/bat/config"

# node
export PATH="$HOME/.nodenv/shims:$HOME/.nodenv/bin:$PATH"
export PATH="$PATH:$HOME/.yarn/bin"

# scala coursier
export PATH="$PATH:$HOME/.local/share/coursier/bin"

# kubectl
(( $+commands[kubectl] )) && [ -d ~/.kube ] && {
    for config in ~/.kube/config*; do
        KUBECONFIG="$KUBECONFIG:$config"
    done
    export KUBECONFIG
}

true
