# zmodload zsh/zprof
bindkey -e # should be on top!

(( $+commands[sheldon] )) || {
    curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh |
        bash -s -- --repo rossmacarthur/sheldon --to ~/bin
}

if [[ $OSTYPE =~ darwin ]]; then
    # Make sure homebrew has higher priority
    export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
fi

# theme
source <(starship init zsh) || warn "failed loading starship."

# You Should Use
export YSU_MODE=ALL

# forgit config
export FORGIT_FZF_DEFAULT_OPTS="--preview-window='right:60%:nohidden'"
export FORGIT_LOG_FZF_OPTS="--height '95%'"

# autosuggest config
export ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(forward-word forward-char)
export ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(end-of-line)

source ~/.zsh_misc
source ~/.zsh_aliases
[ -f ~/.zsh_local  ] && source ~/.zsh_local
[ -f ~/.zsh_secret ] && source ~/.zsh_secret 2>/dev/null # maybe locked
source ~/.zsh_custom
source ~/.zsh_fzf_extra

# Source all the plugins ✨
eval "$(sheldon source)"
